Update all dependencies.
novemberborn/package-hash pull request #37
Opened 2019-01-14 19:44 UTC by coreyfarrell

* Fix test incompatibilities from ava upgrade.
* Update code formatting to deal with linter changes.
* Require node.js 6, drop testing of node.js 4.

2019-01-14 19:45 UTC, coreyfarrell commented
Let me know if as-i-preach rules should be overridden in a different way.

2019-01-14 20:26 UTC, novemberborn requested changes
Yea that’s fine. Could you get rid of AppVeyor and take the Travis config from AVA?

2019-01-14 20:47 UTC, coreyfarrell commented
Appveyor is removed, I copied the travis settings from ava except I added `script: npm run coverage`.

2019-01-15 10:32 UTC, novemberborn approved these changes

2019-01-15 10:33 UTC, merged